- name: Manage Terraform Infrastructure (Test, Apply, or Destroy)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Working directory inside container (mounted from PVC)
    working_dir: "/shared/tfstate"
    # Location of tfvars file
    tfvars_file: "environments/dev/terraform.tfvars"
    # State: 'present' (apply), 'absent' (destroy), 'test' (init + plan only)
    terraform_state: "test"  # Change to 'present' or 'absent'

  tasks:
    # ---------------------------------------------------------
    # 1. Ensure working directory exists
    # ---------------------------------------------------------
    - name: Ensure working directory exists
      ansible.builtin.file:
        path: "{{ working_dir }}"
        state: directory
        mode: '0755'

    # ---------------------------------------------------------
    # 2. Pre-flight: Check backend config file exists
    # ---------------------------------------------------------
    - name: "Log: Check backend config file exists"
      ansible.builtin.stat:
        path: "{{ working_dir }}/backend.tf"
      register: backend_file

    - name: "Fail if backend config file not found"
      ansible.builtin.fail:
        msg: "Backend config file NOT found at {{ working_dir }}/backend.tf"
      when: not backend_file.stat.exists

    # ---------------------------------------------------------
    # 3. Run Terraform Init (Always run)
    # ---------------------------------------------------------
    - name: "Log: Running Terraform Init"
      community.general.terraform:
        project_path: "{{ working_dir }}"
        state: planned
        backend_config:
          path: "terraform.tfstate"
      register: tf_init_result
      ignore_errors: true

    - name: Show Terraform Init Output
      ansible.builtin.debug:
        var: tf_init_result.stdout_lines
      when: tf_init_result.stdout is defined

    - name: Fail if Init failed
      ansible.builtin.fail:
        msg: "Terraform Init failed."
      when: tf_init_result.failed

    # ---------------------------------------------------------
    # 4. Run Terraform Plan (Only if state is 'present' or 'test')
    # ---------------------------------------------------------
    - name: "Log: Running Terraform Plan"
      community.general.terraform:
        project_path: "{{ working_dir }}"
        state: planned
        variables_file: "{{ tfvars_file }}"
        plan_file: "tfplan"
        backend_config:
          path: "terraform.tfstate"
      register: tf_plan_result
      ignore_errors: true
      when: terraform_state in ['present', 'test']

    - name: Show Terraform Plan Output
      ansible.builtin.debug:
        var: tf_plan_result.stdout_lines
      when: terraform_state in ['present', 'test'] and tf_plan_result.stdout is defined

    - name: Fail if Plan failed
      ansible.builtin.fail:
        msg: "Terraform Plan failed."
      when: terraform_state in ['present', 'test'] and tf_plan_result.failed

    # ---------------------------------------------------------
    # 5. Apply (Only if state is 'present')
    # ---------------------------------------------------------
    - name: "Log: Applying Terraform (terraform_state: {{ terraform_state }})"
      community.general.terraform:
        project_path: "{{ working_dir }}"
        state: present
        plan_file: "tfplan"
        backend_config:
          path: "terraform.tfstate"
      register: tf_apply_result
      ignore_errors: true
      when: terraform_state == "present"

    - name: Show Terraform Apply Output
      ansible.builtin.debug:
        var: tf_apply_result.stdout_lines
      when: terraform_state == "present" and tf_apply_result.stdout is defined

    - name: Fail if Apply failed
      ansible.builtin.fail:
        msg: "Terraform Apply failed."
      when: terraform_state == "present" and tf_apply_result.failed

    # ---------------------------------------------------------
    # 6. Destroy (Only if state is 'absent')
    # ---------------------------------------------------------
    - name: "Log: Starting Terraform Destroy"
      community.general.terraform:
        project_path: "{{ working_dir }}"
        state: absent
        variables_file: "{{ tfvars_file }}"
        backend_config:
          path: "terraform.tfstate"
      register: tf_destroy_result
      ignore_errors: true
      when: terraform_state == "absent"

    - name: Show Terraform Destroy Output
      ansible.builtin.debug:
        var: tf_destroy_result.stdout_lines
      when: terraform_state == "absent" and tf_destroy_result.stdout is defined

    - name: Fail if Destroy failed
      ansible.builtin.fail:
        msg: "Terraform Destroy failed."
      when: terraform_state == "absent" and tf_destroy_result.failed

    # ---------------------------------------------------------
    # 7. Final Verification: Check if tfstate file exists
    # ---------------------------------------------------------
    - name: "Log: Checking if terraform.tfstate exists"
      ansible.builtin.stat:
        path: "{{ working_dir }}/terraform.tfstate"
      register: tfstate_file

    - name: "Log: tfstate file found"
      ansible.builtin.debug:
        msg: "terraform.tfstate exists in {{ working_dir }}"
      when: tfstate_file.stat.exists

    - name: "Log: tfstate file NOT found"
      ansible.builtin.fail:
        msg: "terraform.tfstate NOT found in {{ working_dir }}"
      when: not tfstate_file.stat.exists