---
- name: Manage Terraform Infrastructure (Apply & Destroy with Captured State)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    terraform_project_path: "./"
    terraform_state: "present"  # Change to "absent" to destroy
    backend_config_file: "environments/dev/backend.tf"
    tfvars_file: "environments/dev/terraform.tfvars"

  tasks:

    # ---------------------------------------------------------
    # 1. Pre-flight Checks
    # ---------------------------------------------------------
    - name: "Log: Check backend config file exists"
      ansible.builtin.stat:
        path: "{{ terraform_project_path }}/{{ backend_config_file }}"
      register: backend_file

    - name: "Fail if backend config file not found"
      ansible.builtin.assert:
        that:
          - backend_file.stat.exists
        fail_msg: "Backend config file NOT found at {{ terraform_project_path }}/{{ backend_config_file }}"

    # ---------------------------------------------------------
    # 2. Initialize Terraform (Always run)
    # ---------------------------------------------------------
    - name: Run Terraform Init
      ansible.builtin.command:
        cmd: "terraform init -input=false -upgrade -backend-config={{ backend_config_file }}"
        chdir: "{{ terraform_project_path }}"
      register: tf_init_result

    - name: Show Terraform Init Output
      debug:
        var: tf_init_result.stdout_lines

    # ---------------------------------------------------------
    # 3. Plan (Only if state is 'present')
    # ---------------------------------------------------------
    - name: "Log: Generating Terraform Plan"
      debug:
        msg: "Generating Terraform Plan for creation..."
      when: terraform_state == "present"

    - name: Plan Terraform changes
      ansible.builtin.command:
        cmd: "terraform plan -input=false -out=tfplan -var-file={{ tfvars_file }} -no-color"
        chdir: "{{ terraform_project_path }}"
      register: tf_plan_result
      ignore_errors: true
      when: terraform_state == "present"

    - name: Show Terraform Plan Output
      debug:
        var: tf_plan_result.stdout_lines
      when: terraform_state == "present" and tf_plan_result.stdout is defined

    - name: Fail if Plan failed
      fail:
        msg: "Terraform Plan failed. See above logs."
      when: terraform_state == "present" and tf_plan_result.rc != 0

    # ---------------------------------------------------------
    # 4. Apply (Only if state is 'present')
    # ---------------------------------------------------------
    - name: "Log: Applying Terraform Plan"
      debug:
        msg: "Applying the generated tfplan..."
      when: terraform_state == "present"

    - name: Apply Terraform changes
      ansible.builtin.command:
        cmd: "terraform apply -input=false -auto-approve tfplan"
        chdir: "{{ terraform_project_path }}"
      register: tf_apply_result
      ignore_errors: true
      when: terraform_state == "present"

    - name: Show Terraform Apply Output
      debug:
        var: tf_apply_result.stdout_lines
      when: terraform_state == "present" and tf_apply_result.stdout is defined

    - name: Fail if Apply failed
      fail:
        msg: "Terraform Apply failed. See above logs."
      when: terraform_state == "present" and tf_apply_result.rc != 0

    # ---------------------------------------------------------
    # 5. Capture terraform.tfstate after apply (only if present)
    # ---------------------------------------------------------
    - name: "Log: Capturing terraform.tfstate content"
      debug:
        msg: "Capturing terraform.tfstate for reuse in destroy..."
      when: terraform_state == "present"

    - name: Check if terraform.tfstate exists
      ansible.builtin.stat:
        path: "{{ terraform_project_path }}/terraform.tfstate"
      register: tfstate_file

    - name: Fail if terraform.tfstate not found after apply
      fail:
        msg: "terraform.tfstate not found after apply. Check if apply succeeded."
      when: terraform_state == "present" and tfstate_file.stat.exists is false

    - name: Read terraform.tfstate (binary) and decode to JSON
      ansible.builtin.slurp:
        src: "{{ terraform_project_path }}/terraform.tfstate"
      register: tfstate_content

    - name: Store tfstate content as JSON fact
      ansible.builtin.set_fact:
        tfstate_json: "{{ (tfstate_content.content | b64decode) | from_json }}"
      no_log: true
      when: terraform_state == "present"

    - name: Show captured state summary
      debug:
        msg: |
          Captured Terraform State:
            - Resources: {{ tfstate_json.resources | length }}
            - Terraform Version: {{ tfstate_json.terraform_version }}
            - Backend: {{ tfstate_json.backend.type }}
      when: terraform_state == "present"

    # ---------------------------------------------------------
    # 6. Destroy Infrastructure (Only if state is 'absent')
    # ---------------------------------------------------------
    - name: "Log: Starting Terraform Destroy using captured state"
      debug:
        msg: "Destroying infrastructure using captured terraform.tfstate content..."
      when: terraform_state == "absent"

    - name: "Ensure backend is configured for destroy"
      ansible.builtin.set_fact:
        backend_config: "{{ {'config_path': backend_config_file} }}"

    # Create temp file from captured state
    - name: Create temporary tfstate file from captured content
      ansible.builtin.copy:
        content: "{{ tfstate_json | to_json | replace('\n', '') }}"
        dest: "{{ ansible_env.AWX_PROJECT_PATH }}/temp.tfstate"
        mode: '0600'
      when: terraform_state == "absent"

    # Push captured state to backend
    - name: Push captured state to backend
      ansible.builtin.command:
        cmd: "terraform state push -state=-- ./temp.tfstate"
        chdir: "{{ terraform_project_path }}"
      register: tf_state_push
      ignore_errors: true
      when: terraform_state == "absent"

    - name: Fail if state push failed
      fail:
        msg: "Failed to push captured state to backend: {{ tf_state_push.msg }}"
      when: terraform_state == "absent" and tf_state_push.failed

    # Now run destroy (using state from backend)
    - name: Destroy Terraform Infrastructure
      ansible.builtin.command:
        cmd: "terraform destroy -input=false -auto-approve"
        chdir: "{{ terraform_project_path }}"
      register: tf_destroy_result
      ignore_errors: true
      when: terraform_state == "absent"

    - name: Show Terraform Destroy Output
      debug:
        var: tf_destroy_result.stdout_lines
      when: terraform_state == "absent" and tf_destroy_result.stdout is defined

    - name: Fail if Destroy failed
      fail:
        msg: "Terraform Destroy failed: {{ tf_destroy_result.msg }}"
      when: terraform_state == "absent" and tf_destroy_result.rc != 0

    # ---------------------------------------------------------
    # 7. Cleanup (Optional)
    # ---------------------------------------------------------
    - name: Remove temp.tfstate file
      ansible.builtin.file:
        path: "{{ ansible_env.AWX_PROJECT_PATH }}/temp.tfstate"
        state: absent